### ISSUE TITLE
Cyberpunk 2077: Crashes after first logo on AMD

### ISSUE THREAD

**Issue by JonesGreen** [HansKristian-Work/vkd3d-proton#461] opened 2020-12-12 10:12 UTC
Hi @ all

I'm on proton 5.13-4, mesa-git and use a AMD Vega 56. I attached all additional info at the bottom.
On release the game did not work and would always crash after the first logo.
With the new game patch 1.04 the game worked ! I played for about 2 hours without any problems. (No change was made to mesa-git)
After that I quit the game because I had something else to do. But now the game behaves like before and will not start and in result gives me colorful pixel noise on screen.
I'm not sure if this a radv, game bug or vkd3d-proton bug. There are quite a few errors in the proton log, but I don't now if these are "normal" at this stage. If you require more information I will try to provide them. Thanks for your great work !

[steam-1091500.log](https://github.com/HansKristian-Work/vkd3d-proton/files/5682849/steam-1091500.log)
[vulkaninfo.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/5682851/vulkaninfo.txt)
[dmesg.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/5682853/dmesg.txt)
[systeminfo.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/5682856/systeminfo.txt)
[screen](https://user-images.githubusercontent.com/43512610/101981165-27b0d680-3c6b-11eb-999f-9c7582d3f086.jpg)

**Comment by doitsujin** [comment] 2020-12-12 10:19
So there's a whole bunch of prose here but I'm missing one crucial detail: How can we reproduce this?

You're just getting a GPU hang, this isn't really expected but also not surprising considering how hopelessly broken the game is. We should probably not advertize the game as supported just yet though.

**Comment by JonesGreen** [comment] 2020-12-12 10:26
Thank you for your very fast response. What would be a way so that you could reproduce this? If you can give me a tip how I can provide something, I will try it.

**Comment by HansKristian-Work** [comment] 2020-12-12 12:03
I can reproduce it on 1.04 with 5700xt, but it is completely random, and knowing how broken the game is, I'm going to assume the game is buggy for the time being.

**Comment by screwylightbulb** [comment] 2020-12-12 17:37
> So there's a whole bunch of prose here but I'm missing one crucial detail: How can we reproduce this?
> 
> You're just getting a GPU hang, this isn't really expected but also not surprising considering how hopelessly broken the game is. We should probably not advertize the game as supported just yet though.

I also had one GPU hang yesterday using an AMD setup. This was before the 1.04 patch. I did not bug report because I also cannot say how to reproduce. I do not have a log either, and it only happened after having the game running for about 8 hours. I was tabbed out at the time to my browser and went off to have a shower. When I got back my system was frozen and the whole screen was covered in some trippy coloured blocks.

**Comment by screwylightbulb** [comment] 2020-12-12 17:46
I think most problems that exist right now should be fixed by CDPR, since I suspect vkd3d is already behaving as it should. Not sure if there's any communication with them though.

**Comment by JonesGreen** [comment] 2020-12-14 01:51
After some more testing I found the culprit on my machine for the my gpu hang on startup.
It is the steam overlay. When I disable the steam overlay for Cyberpunk 2077 the game starts up just fine.
As soon as the overlay is enabled I get a gpu hang directly after the first logo everytime.

**Comment by screwylightbulb** [comment] 2020-12-14 07:07
Wow, we have a fun one here. This is on an NVidia RTX 2070 Super. This is at the Relic stealing mission. When walking towards the secuirity scanner, everything goes black, and it stays black, even going through and up the elevator. 

This should probably be a new issue with logs and such, but at the moment it might not be worth chasing after every such bug in proton when there are so many in-game bugs upstream.

See: [https://youtu.be/D0i-0JB9D50](url)

**Comment by DistantThunder** [comment] 2020-12-14 10:46
>gives me colorful pixel noise on screen.

Just to chime in, I had this exact crash on Mesa-git on the game with patch 1.0.4 yesterday on 5700XT, but never at boot. It's a shame AMDGPU can't prevent itself from hard crashes like this (my machine rebooted...).

**Comment by screwylightbulb** [comment] 2020-12-14 10:57
> Wow, we have a fun one here. This is on an NVidia RTX 2070 Super. This is at the Relic stealing mission. When walking towards the secuirity scanner, everything goes black, and it stays black, even going through and up the elevator.
> 
> This should probably be a new issue with logs and such, but at the moment it might not be worth chasing after every such bug in proton when there are so many in-game bugs upstream.
> 
> See: [https://youtu.be/D0i-0JB9D50](url)

Just had this happen again where you meet with Dex at the motel. Also found that when activating the scanner that works normally. So I guess it's a post processing effect of some sort causing it. Maybe I should just record some logs and pass it on.

**Comment by doitsujin** [comment] 2020-12-14 11:26
> This is on an NVidia RTX 2070 Super.

The game is currently expected not to work properly until either Nvidia implements the mutable descriptor type extension or CDPR fix their broken descriptor management. This can include crashes and broken rendering.

**Comment by screwylightbulb** [comment] 2020-12-14 11:47
> > This is on an NVidia RTX 2070 Super.
> 
> The game is currently expected not to work properly until either Nvidia implements the mutable descriptor type extension or CDPR fix their broken descriptor management. This can include crashes and broken rendering.

Fully aware.

**Comment by JonesGreen** [comment] 2020-12-15 14:56
Finally got it to work. I used that fix described here https://gitlab.freedesktop.org/mesa/mesa/-/issues/3960#note_728911
I only changed it to EB3033C9B8010000000FA28BC8C1F908 which is supposed the right replacement for the 1.04 patch.
With this I can always reproduce this. Original .exe == always gpu hang and the modified .exe just works. When started up with the  modified .exe the game works well. (About 7 hours in and no gpu hang.)
But I also cannot explain why this tweak fixes the gpu hang.

**Comment by RoyShapiro** [comment] 2020-12-18 17:02
@JonesGreen Thanks so much for posting this!

Surprise-surprise, it **fixes** the game (or at least a part thereof) for me, even though I'm on **NVidia GPU** with AMD processor!

Previously couldn't get through a "no-save" interactive cutscene (during a certain border car chase in the beginning of the game), with 100% reproducible complete freeze (with a known entry in syslog regarding a GPU malfunction) within 25 seconds - 1.5 minutes into the sequence. Now it Just Works!(tm), at least I've been able to complete the interactive cutscene without issue.

That said, I do notice strange graphical glitches, such as misbehaving view distance for things such as shrubs & remote neon lamps appearing too close to me, and not rendering to their proper full-detailed view until I get very close. Like, really close.
I've also lost about 20 fps from reported performance (monitored via Mangohud), I used to have ~50 fps on all Ultras on 1440, and now I have about ~ 30 fps on average.

Specs: AMD Threadripper 1920X, RTX 3090, Proton 5.13-4, Vkd3d-Proton built from commit https://github.com/HansKristian-Work/vkd3d-proton/commit/946bcd7922f77bf68636589b068998d414c2f853, Nvidia driver 455.46.02

**Comment by Blisto91** [comment] 2023-01-02 21:17
@JonesGreen Friendly necro ping. Is it safe to assume that this issue has been resolved with game and driver updates?

**Comment by JonesGreen** [comment] 2023-01-03 09:37
> @JonesGreen Friendly necro ping. Is it safe to assume that this issue has been resolved with game and driver updates?

Yes it is not an issue on my end anymore. Though I use a AMD 6700 XT now.

**Comment by DistantThunder** [comment] 2023-01-03 11:06
No problem here as well, can be closed I think.

**Closed** 2023-01-03 11:08 UTC
