### ISSUE TITLE
Monster hunter world bug

### ISSUE THREAD

**Issue by JorgeMoya41** [HansKristian-Work/vkd3d-proton#113] opened 2020-04-30 22:12 UTC
When high graphic quality is activated the game behaves strange. I used the vkd3d form Proton 5.0-7. Launch option: VKD3D_FEATURE_LEVEL=12_0

System information:
rx 580 /Mesa 19.3.4 +ACO
ryzen 7 2700x /5.6.4-152.current

https://youtu.be/SYiz1bGHKlk

**Comment by doitsujin** [comment] 2020-05-02 09:28
Please re-test on a newer mesa version, at least 20.0.

**Comment by JorgeMoya41** [comment] 2020-05-03 01:58
Thanks, I'll try it , but don't expect anything very soon because I'm new to these things and maybe break my Linux machine many times before it works. :sweat_smile:

**Comment by JorgeMoya41** [comment] 2020-05-08 05:06
Hi, I haven't been able to update the drivers yet, but today I was able to play for a while and discovered that the problem occurs with image quality high and screen space reflection disabled. Sorry for the inconvenience.

https://youtu.be/BEF20vRh9Ug

**Comment by doitsujin** [comment] 2020-05-18 11:14
I'm able to reproduce the problem with the given game settings, but this seems to be caused by the game writing incorrect data to certain uniform buffers. Not sure if this is really our bug or not.

**Comment by JorgeMoya41** [comment] 2020-05-20 13:43
Well, I guess it won't be necessary to manually update the drivers.
Thank you very much for taking the time to inspect it.

**Comment by nutta-git** [comment] 2020-06-06 07:43
Same issue happened to me and enabling screen space reflection has fixed the issue. 
https://streamable.com/t2i2vh

**Comment by doitsujin** [comment] 2020-11-06 15:08
Seems to be fixed as of latest `master`, please retest.

**Comment by nutta-git** [comment] 2020-11-06 16:19
The waterfall issue has be fixed for me; however there seems to be a new issue. 
Dx12 introduces flickering. (Should I make a new Issue Ticket?)  https://streamable.com/9hpnhq

Specs:
os: Arch Linux 
kernel: 5.9.4-zen1-1-zen 
cpu/gpu: 3700x/ rx5700
driver: mesa 20.2.1-1

**Comment by doitsujin** [comment] 2020-11-12 15:32
I'm unable to reproduce that on my end.

**Comment by nutta-git** [comment] 2020-11-13 08:06
**Enviroment**:
proton_tkg_5.21.r4.gcd3ee9b2
mesa-tkg-git 21.0.0_devel.131041.3fa3bc19a28-1
**Description**:  
So I went to different areas of the game, Ancient Forest, Elder Recess and Hoarfrost. They all showed flickering, but looking at the map the flickering stopped. 
**Log**: 
file-size(70+MB) is too big for Github 
https://filebin.net/diiqrhmdt7szwizx (the file will delete in 1 week)

**Comment by doitsujin** [comment] 2020-11-13 11:05
Logs aren't super useful to debug rendering issues.

**Comment by JorgeMoya41** [comment] 2020-11-13 22:21
Sorry for the delay in answering. I confirm that the problem has been fixed and I have not seen any other issue.

Just in case, tested in:
rx 580 / Mesa 20.2.1
ryzen 7 2700x /5.8.18-1
proton 5.13-2

(Thank you so much for everything)

**Comment by nutta-git** [comment] 2020-11-18 19:29
The issue is solved! Looks like a amdvlk issue. 

Background: 
So I decided to run mangohud and noticed that amdvlk was running instead of mesa. Removing amdvlk forces steam to run mesa and now the game runs fine using dx12. 

Sorry for wasting your time, I always assumed mesa was running instead of amdvlk. 
Thank you!

**Closed** 2020-11-19 00:12 UTC
