### ISSUE TITLE
Regression in vkd3d-proton-2.4

### ISSUE THREAD

**Issue by imamhs** [HansKristian-Work/vkd3d-proton#748] opened 2021-07-21 00:41 UTC
Running Hitman 3 with the version 2.4 crashes the game with the following message. I checked my driver it supports VK_KHR_separate_depth_stencil_layouts extension. The game loads fine with version 2.3.1.

info:  Game: hitman3.exe
info:  DXVK: v1.8.1
info:  Found built-in config:
info:  Effective configuration:
info:    dxgi.customVendorId = 10de
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  NVIDIA GeForce GTX 1650:
info:    Driver: 470.57.2
info:    Vulkan: 1.2.175
info:    Memory Heap[0]: 
info:      Size: 4096 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11978 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  Adapter LUID 0: 0:401
65:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
65:info:vkd3d_instance_init: vkd3d-proton - build: cafe99e223296e2.
65:err:vkd3d_init_device_caps: separateDepthStencilLayouts is not supported by this implementation. This is required for correct operation.

My system configuration is:

PC:

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
16 GB RAM
GeForce GTX 1650 4 GB

System:

Kubuntu 20.10 64 Bit
Liquorix Linux kernel (5.12.0-17.2-liquorix-amd64)
Wine version: 5.0
Nvidia GTX driver version 470 (470.57.02)
Vulkan Version: 1.2.141

**Comment by HansKristian-Work** [comment] 2021-07-21 12:30
This is a required extension and all NV GPUs support that. Either you have an ancient driver or very old Proton which doesn't understand that extension.

**Comment by imamhs** [comment] 2021-07-21 13:02
As you can see I have latest Nvidia driver and the only thing could go wrong is using old Wine version 5.0, I am going to test it against latest Wine version

**Comment by HansKristian-Work** [comment] 2021-07-21 13:06
Right, in that case it's most likely a very old winevulkan.

**Comment by HansKristian-Work** [comment] 2021-07-21 16:35
This is an NV bug with runtimes, see https://github.com/HansKristian-Work/vkd3d-proton/issues/711#issuecomment-867000702 for a workaround.

**Comment by imamhs** [comment] 2021-07-21 20:35
nvidia-modprobe -u -c=0 worked and the game loads normally, Thank you

But there is another issue which maybe not related but has to do with NV driver, the system freezes completely while loading a level or after playing a level for a while

**Comment by Oschowa** [comment] 2021-07-21 21:45
Can you check if you are running out of system RAM when those freezes happen? Multiple people have reported that the nvidia 470 drivers seem to eat a lot of memory, especially with vkd3d-proton titles.

**Comment by tris-tan** [comment] 2021-07-21 22:03
Yep, I'm having 30GB of RAM/page file use trying to play HZD. It was fine before the new nvidia release.

Manjaro on 5.10.49 kernel, Nvidia 470.42.01.
Proton-GE/Experimental using VKD3D.

**Comment by Draguljche** [comment] 2021-07-24 20:43
It is same for me on Garuda Linux KDE with 16GB of RAM and GTX1080 on nvidia-dkms 470.57.02 driver and custom kernel.

**Comment by imamhs** [comment] 2021-07-25 02:22
I can not confirm if it is NV eating up ram since the system freezes completely and I had to restart

**Comment by FatehAK** [comment] 2021-07-25 15:54
I have posted this issue on NVIDIA forums as well. Please do share reports there too so it gets noticed.

https://forums.developer.nvidia.com/t/high-ram-consumption-when-playing-dx12-games-nvidia-470-57-02-drivers/184635

**Comment by Draguljche** [comment] 2021-07-25 19:15
Ok, I tried to delete prefix and then start game fresh without saves and anything, now it crash at startup...

**Comment by enveeed** [comment] 2021-07-26 22:49
I can confirm the RAM issue on the 470 driver with Hitman 2 running on vkd3d-proton, however I was not able to check what exactly uses the memory. The game itself just crashes when the system is out of memory and goes back to normal, I can just restart the game and play a bit until its out of memory again and crashes. Does not happen on the 465 branch.

**Comment by dsuserds** [comment] 2021-07-28 08:30
I also can't play Horizon Zero: Dawn because it uses too much memory. I can load a single save but every fast travel fails because the RAM usage goes to max(16GB) after a few seconds.
I can force-quit the game when it's frozen. I'm using the 470.42.01 driver too. The game also has heavy cpu bottlenecking with an 5900x.

**Comment by enveeed** [comment] 2021-07-29 22:04
I have confirmed it is the game process itself eating the memory, I've also captured this pmap output of the process but I do not know how to interpret it, maybe it can help someone debug the issue:

[pmap.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6903878/pmap.log)

**Comment by enveeed** [comment] 2021-07-29 22:25
We might be on the wrong track here, I've just downgraded to the 460 driver branch (last released in may) and the issue persists.

**Comment by folknor** [comment] 2021-08-22 06:47
> However, using older Proton releases and consequently older vkd3d-proton versions fixes the problem for me on the older driver branch, I've not yet tested if this is the case on the new driver branch as well.

Specifically which Proton release and driver release are you using?

**Comment by imamhs** [comment] 2021-08-22 14:22
With latest NVIDIA 470.63.01 driver works with vkd3d-proton-2.3.1 but not vkd3d-proton-2.4 as usual

**Comment by HansKristian-Work** [comment] 2021-09-07 11:36
There is a workaround for massive NV memory usage on master now.

**Closed by HansKristian-Work** 2021-09-07 11:36 UTC

**Comment by imamhs** [comment] 2021-11-01 19:08
Latest vkd3d-proton-2.5 and NVIDIA 470.82.00 the game (Hitman 3) crashes but it does not freeze computer.
