### ISSUE TITLE
Forza Horizon 4 Car Texture Issue

### ISSUE THREAD

**Issue by kodatarule** [HansKristian-Work/vkd3d-proton#1199] opened 2022-08-23 18:48 UTC
It seems that on the latest vkd3d-proton(which includes the Halo Infinite shared resources patches)
The game doesn't seem to load car textures in-game. 
Will provide screenshots a little bit later.

Attaching screenshots of the issue:
![20220824080017_1](https://user-images.githubusercontent.com/65848953/186333017-e0a84863-8fd5-487f-921d-e5c7753c285c.jpg)
![20220824080050_1](https://user-images.githubusercontent.com/65848953/186333019-eb7a5bff-1b2a-4b6a-9ed9-7040f1a89717.jpg)
![20220824080109_1](https://user-images.githubusercontent.com/65848953/186333020-99e5e7e5-6cf5-4c16-a528-a7021bdc65b5.jpg)
![20220824080110_1](https://user-images.githubusercontent.com/65848953/186333023-47b3c592-0e69-4829-a4e9-bfb1122f5687.jpg)

![20220824075957_1](https://user-images.githubusercontent.com/65848953/186333010-b56967a1-07f3-4edb-8661-12b73b2053f1.jpg)
![20220824080015_1](https://user-images.githubusercontent.com/65848953/186333013-3cef32cf-b2d4-4b6b-bc10-ad8e63fed3eb.jpg)

**Comment by HansKristian-Work** [comment] 2022-09-01 13:50
Does this reproduce for you in the benchmark? I cannot reproduce it there, and I generally have some issues with CPU crashes unrelated to vkd3d-proton for some reason, so don't think I can get to that part of the game ...

**Comment by kodatarule** [comment] 2022-09-01 21:03
Running the benchmark did fix the issue even for standard driving, I am unable to reproduce it now on proton experimental(having the Halo Infinite patches). 
Were there any changes to VKD3D-Proton made recently ?

**Comment by HansKristian-Work** [comment] 2022-09-06 09:27
Not any I can think of that would fix this. Might be that Experimental pulled in some changes.

**Comment by HansKristian-Work** [comment] 2022-09-09 12:49
Seems like it's okay to close this now.

**Closed by HansKristian-Work** 2022-09-09 12:49 UTC
