### ISSUE TITLE
Cyberpunk 2077 freezes in settings menu with VK_NV_low_latency2

### ISSUE THREAD

**Issue by runar-work** [HansKristian-Work/vkd3d-proton#1929] opened 2024-03-06 17:59 UTC
After 2-5 minutes in the settings menu, the game will freeze. It's not a GPU hang, as there is nothing of note in the kernel log. It seemed safe to assume that if there was no freeze after at least 5 minutes it wouldn't happen, so I was able to do a bisect. I also tried in-game for about 7 minutes without issue, but when I went into the menu from there it froze instantly. 

I also tested various other Wine versions, like Proton 8.0-5 and experimental bleeding-edge 8.0, but I was only able to trigger this with bleeding-edge 9.0.

### Software information
Cyberpunk 2077 with graphics preset low, vsync off and reflex off.

### System information
- GPU: RTX 3070
- Driver: 550.54.14 and 550.40.53
- Wine version: 1709736443 experimental-bleeding-edge-9.0-84317-20240306-pe5aac5-wd78dcf-d4b0e31-vbd1af8
- VKD3D-Proton version: https://github.com/HansKristian-Work/vkd3d-proton/commit/0eb04f89c560e28acd352f05b727ad4c6ddb5b45

### Log files
[steam-1091500_first_bad_commit.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/14513734/steam-1091500_first_bad_commit.zip)

**Comment by Blisto91** [comment] 2024-03-06 19:20
Another game that hits this issue is Hitman 3. Freezes after a bit even in menus.
Behavior stops when launched with `VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2`

**Comment by esullivan-nvidia** [comment] 2024-03-07 06:58
Are either of you able to reproduce the issue with this commit?

https://github.com/esullivan-nvidia/vkd3d-proton/commit/0d7b62683b247b05df235d85dcb90887a729f7b1

**Comment by runar-work** [comment] 2024-03-07 11:23
@esullivan-nvidia That commit fixes the Cyberpunk freeze for me.

**Comment by HansKristian-Work** [comment] 2024-03-07 13:32
This looks like a driver bug to me. @esullivan-nvidia will you file a PR with that fix? We're in RC phase now, so this fix should land ASAP.

**Comment by Blisto91** [comment] 2024-03-07 17:16
I can also confirm that the commit helps Hitman 3

**Comment by esullivan-nvidia** [comment] 2024-03-07 19:09
Agreed that this is most likely a driver bug, I have not been able to root cause it yet though. This should function well enough as a workaround for now. I will create a PR.

**Comment by HansKristian-Work** [comment] 2024-03-12 18:10
Closing as we have a WAR in place.

**Closed by HansKristian-Work** 2024-03-12 18:10 UTC
