### ISSUE TITLE
Add VKD3D_FRAME_RATE environment variable

### ISSUE THREAD

**Issue by Tiagoquix** [HansKristian-Work/vkd3d-proton#1998] opened 2024-05-26 21:13 UTC
Basically the same as DXVK.

https://github.com/doitsujin/dxvk?tab=readme-ov-file#frame-rate-limit

https://github.com/doitsujin/dxvk/blob/master/src/util/util_fps_limiter.cpp

What would also be interesting would be to make this DXVK frame rate environment variable also work in VKD3D without having to create a new separate one just for VKD3D, but I don't know if it's possible because I imagine that the projects (DXVK and VKD3D) can be used independently one from the other.

One possible approach would be to create a variable with a "global" name (that is compatible with both projects) and recommend it as the new one, at the same time that `DXVK_FRAME_RATE` and `VKD3D_FRAME_RATE` would work with this new "global" variable (basically creating aliases).

**Comment by HansKristian-Work** [comment] 2024-05-27 15:26
DXVK owns the outer DXGI layer for vkd3d-proton. Wouldn't DXVK's frame limiter apply to vkd3d-proton as well?

**Comment by doitsujin** [comment] 2024-05-27 16:12
DXVK's frame rate limiter actually runs on the same thread that handles present waits and feeds back into app logic that way, rather than blocking DXGI present directly. We tried doing that in the initial implementation, but for some reason that caused some catastrophic frame pacing issues.

If we want this to work we'd probably want to bring our own logic and extend the swap chain interface further, so that DXVK config options also get applied properly. An argument for doing that would be something like supporting 60 Hz display modes in an environment that does not support mode switches (i.e. Proton), which is something I've been wanting to do in DXVK anyway.

**Comment by shelterx** [comment] 2024-05-30 09:41
https://github.com/HansKristian-Work/vkd3d-proton/issues/1553

**Comment by doitsujin** [comment] 2024-06-18 19:16
https://github.com/HansKristian-Work/vkd3d-proton/pull/2014 tentatively implements this.

**Comment by doitsujin** [comment] 2024-06-18 19:32
The current implementation supports `DXVK_FRAME_RATE`, using any names that imply it applies to anything outside of dxvk/vkd3d-proton is **not** desireable since native Vulkan games exist.

**Comment by shelterx** [comment] 2024-06-19 06:55
I get what you mean but honestly, DXVK/VKD3D do not share the same variables. I think a shared variable will add confusion and breaks the approach the project uses.

**Comment by doitsujin** [comment] 2024-06-19 21:49
I still don't understand what the problem is, `DXVK_FRAME_RATE` applies to both DXVK **and** the PR, why do we need to give it some turbocursed name that nobody is going to be able to remember?

**Comment by shelterx** [comment] 2024-06-23 05:07
Well, I'm not a newcomer to gaming in Linux anymore but I was. And the whole VKD3D/DXVK/proton/heroic/bottles/lutris thing was very confusing at first. I don't think a single variables naming will matter much. It's not my thing to decide but my logic really says NO! when using a DXVK variable in vkd3d-proton.

**Comment by doitsujin** [comment] 2024-06-25 10:32
No, and for the 10th time, I *really* don't see why this is such a huge problem when we have a) the DXVK alias that works for both and b) dxvk.conf overrides which also work for both.

Anyway, merged.

**Closed by doitsujin** 2024-06-25 10:32 UTC
