### ISSUE TITLE
Ratchet & Clank - blocky corruption when looking at rift portals

### ISSUE THREAD

**Issue by aufkrawall** [HansKristian-Work/vkd3d-proton#1833] opened 2024-01-13 21:58 UTC
There is blocky corruption when looking at rift portals:
![1895880_20240112000035_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/3169d389-58ab-4bdf-85ed-01cedb1d685b)

Happens with both RADV & amdvlk. Doesn't happen with native D3D12. Issue seems to disappear at some rendering/upsampling resolutions, but happens at most of them and also native 1440p TAA.

### Software information
Ratchet & Clank, latest Steam version, maximum settings (RT off), TAA, 1440p

### System information
- GPU: RX 7800 XT
- Driver: RADV mesa-git 183253.e36235e6d53 / amdvlk v-2023.Q4.3
- Wine version: Proton Experimental
- VKD3D-Proton version: 12f561cfe2156714ba17d3322230b87b65739714

### Log files
[steam-1895880.7z.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/13929597/steam-1895880.7z.zip)

**Comment by Blisto91** [comment] 2024-01-13 22:00
Can you highlight where on the image the issue is? I'm not sure i see it

**Comment by aufkrawall** [comment] 2024-01-13 22:02
Sure:
![1895880_20240112000035_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/c901126d-9520-49cd-9369-0d26d40ae3ca)

**Comment by Blisto91** [comment] 2024-01-13 22:28
I haven't been able to reproduce this ingame at the same spot so far with either amdvlk or radv on my RX 6800. I have 108op monitor but tried faking 1440p with gamescope and also tried different upscaling.

Will try again with rdna3 later.

**Comment by aufkrawall** [comment] 2024-01-13 22:34
Thanks!

For whatever reason, I now can't reproduce with 100% TAA anymore either. But with any upscaler set to "quality", it triggers the issue:
![1895880_20240113233318_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/c133ac60-d0c4-4dc0-9a7b-29f7d9859c57) 
![1895880_20240113233306_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/e1edbcc5-3770-4608-8799-798c32446d57)

**Comment by aufkrawall** [comment] 2024-01-13 22:36
The issue seems to be caused by XeGTAO.

**Comment by Blisto91** [comment] 2024-01-13 23:05
Okay sorry yes i can reproduce it now.

Attached a Vulkan renderdoc capture made with XeGTAO and XeSS on a RX 6800 with radv 23.3.3. Notice that the right side of the portal is darker which is the side with the glitching (it can move with the camera)
https://drive.proton.me/urls/Y0XQZRP5G0#zSl7mhPv75bL

**Comment by HansKristian-Work** [comment] 2024-01-19 13:51
I reproduce this on Windows too.

![portal-bug](https://github.com/HansKristian-Work/vkd3d-proton/assets/17786731/9100a141-3644-43e5-9ce3-d6907ee75911)

**Comment by HansKristian-Work** [comment] 2024-01-19 13:57
The portal rendering seems to be contained within a bounding box.

There is an offset applies to the GlobalThreadID when writing the input to XeGTAO buffers.

![copy_input](https://github.com/HansKristian-Work/vkd3d-proton/assets/17786731/6e34e620-16ee-44a5-9c54-8b94bd37dfcc)

But in the CS_XeGtaoFinalize pass, there is no offset in the shader, so the portal AO gets a sliced copy.

![final](https://github.com/HansKristian-Work/vkd3d-proton/assets/17786731/f1ffbdb8-f43d-49c5-bca7-76fcb4e90634)

![final2](https://github.com/HansKristian-Work/vkd3d-proton/assets/17786731/56034db6-c148-4aeb-a6b1-7b3cdfc446bf)

That causes either darkening or garbage in the right half.

**Comment by HansKristian-Work** [comment] 2024-01-19 13:57
Closing as not our bug.

**Closed by HansKristian-Work** 2024-01-19 13:57 UTC

**Comment by aufkrawall** [comment] 2024-01-19 16:45
Thanks for looking into this and your detailed explanation, really appreciated! I guess then it's hardly noticeable on Windows for some random/racy reasons.

Btw. did you notice that some textures aren't streamed in full resolution with VKD3D-Proton? It seems to match the result on Windows when you delete the DirectStorage DLLs there.
![1895880_20240119173548_1](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/20e24fd5-858d-424d-ad66-2a4257e231fa)

Windows with DS:
![RiftApart_2024_01_19_17_41_25_268](https://github.com/HansKristian-Work/vkd3d-proton/assets/13510490/f89b152e-7856-4a47-b22e-c49a1303a873)

This is right after loading the level for the first time, no RT.

**Comment by aufkrawall** [comment] 2024-02-01 20:45
@Blisto91 Can I convince you to check whether you can confirm the texture issue? :)
