### ISSUE TITLE
UE5 Lyra demo hits a regression in 2.11 when running on Tesla T4

### ISSUE THREAD

**Issue by nsivov** [HansKristian-Work/vkd3d-proton#1858] opened 2024-01-29 20:54 UTC
The game hangs on start in quickplay mode, when global illumination setting is High or Epic.

Linking the build here https://drive.google.com/file/d/1-umg2KGCh-Dom3EY07ToNmrZ-ibVl7o3/view?usp=sharing, it's distributed as UE source project normally.

This is a regression from 4f2a82916ebd8ad6c70be841f429786951d13d58. Even though the driver does not support VK_EXT_image_compression_control, other changes in the same commit enable a path that previously was guarded by config flags.

### Software information
UE5 demo Lyra (https://www.unrealengine.com/marketplace/en-US/product/lyra)

### System information
- GPU: Nvidia Tesla T4
- Driver: 545.33
- Wine version: proton experimental 8.0
- VKD3D-Proton version: 2.11

### Log files

Attaching dmesg hang message, and corresponding wine log.

[dmesg.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/14089440/dmesg.txt)
[lyra.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14089445/lyra.log)

**Comment by HansKristian-Work** [comment] 2024-01-31 11:37
I can reproduce this on RTX 4070 and 545.29.06. Extremely weird.

**Comment by HansKristian-Work** [comment] 2024-01-31 13:23
Turned it was caused by lack of BLOCK_VIEW_COMPAT, but MUTABLE itself. Curious that NV driver cared about it this much, but fixed now. Thanks for the find.

**Closed** 2024-01-31 13:31 UTC
