### ISSUE TITLE
Diablo 2 resurrected still black screen after installing hanskristian fix

### ISSUE THREAD

**Issue by d2rgaming-9000** [HansKristian-Work/vkd3d-proton#818] opened 2021-09-27 23:51 UTC
Hey I installed vkd3d-proton provided https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/1130860939.
Here are the steps that I followed for the supposed fix.
1. ran the .sh script and installed it.
2. created a file d2r-dxvk-patched in ~/.local/share/lutris/runtime/dxvk
3. copied the x86 x64 files into D2R directory
4. Run EXE inside wine prefix "Game.exe".
The game launches with sounds but black screen.

The supposed fix was suggested by some kind people on reddit, but alas it does not seem to be working for me and yes I am missing a step and that is configuring lutris to install d2r as d2r-dxvk-patched "manual" dxvk version, but i do not know how to do that. When I go to the lutris search area and type in diablo, then click on install "Diablo II: Resurrected" no window shows up there.
But I have it already installed via battlenet, via heroes of the storm.

My issue is more complicated it as I have battlenet installed via heroes of the storm using lutris.
I wish there is a more clear way of doing it. The initial advise that was given here was to basically just install the script and run the exe game.exe.

I am using GTX 670 mx and latest wine.

**Comment by iWeaker4you** [comment] 2021-09-28 01:08
I think it's a driver problem, the GTX 670 stopped having support for a long time, I think its latest drivers are the 390 .. and it lacks many extensions and Vulkan optimizations.

**Comment by jerrytt** [comment] 2021-09-28 02:15
I've same issue on  nvidia  960m card on my laptop.

what i can confirm is  driver/hardware issue :

I use Manjaro_OS  on usb(ssd) disk which can boot on any machine  with same software env.

i7 + nvidia 960m card :
  1 backscreen
  2 mouse can rander correctly .
  3 d2r run on windows without issue

i9  + nvidia t1000 card:
   1 run "nvidia-modprobe -u -c=0" first
   2 running game without problem
   3 d2r run on windows without issue

**Comment by jerrytt** [comment] 2021-09-28 02:20
> I wish there is a more clear way of doing it. The initial advise that was given here was to basically just install the script and run the exe game.exe.
> 
> I am using GTX 670 mx and latest wine.
I think dxvk 1.9.1L-2 are patched. nothing need to do if you set your dxvk correct version.

**Comment by K0bin** [comment] 2021-09-28 07:43
As far as I know Lutris should ship a version of vkd3d-proton that has the fix.

**Comment by karolmateusznowak** [comment] 2021-09-30 16:34
D2R starts and works properly till the welcome screen:
![Screenshot_2021-09-30_18-21-49](https://user-images.githubusercontent.com/38962868/135494461-9b786bfc-9d40-4692-8935-5bf643709576.png)

After any key is pressed, D2R freezes

Terminal logs:
```
MESA-INTEL: error: ../src/intel/vulkan/anv_device.c:3713: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
01e0:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
01e0:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
01e0:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
01e0:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
```

My Setup Is:
Ubuntu 21.04
Intel UHD 620
vkd3d-proton built from the latest source code




Did anybody manage to run D2R without any problems on Intel UHD 620?

**Comment by K0bin** [comment] 2021-09-30 18:08
That's most likely an ANV issue. I don't think anything works with VKD3D-Proton on ANV.

**Comment by Pilvinen** [comment] 2021-10-13 12:27
I'm am just an end user so you'll have to be more specific on what you need and from where and how if you need more information. There's very little information available on Google how these things work.

![image](https://user-images.githubusercontent.com/4374351/137131033-806686ba-4e43-4a04-ac2e-994e09532e72.png)

This is what I'm seeing on Lutris config for runner options. I've tried changing the versions but nothing seems to make a difference.

When I right click the runner and select "show logs" I get this:

![image](https://user-images.githubusercontent.com/4374351/137131930-f1c1fd69-84ac-4a5a-aeeb-bc9e56dea33a.png)

I'm not sure if this is the vk3d3-proton logs you requested or not, but you didn't give more specific instructions where to find them and Google wasn't helpful on this.

**Comment by K0bin** [comment] 2021-10-20 14:05
> The minimum supported GPU according to Blizzard is GTX 660, so in theory it is supported and should work on GTX 750 Ti on hardware side at least.

The only supported OS according to Blizzard is also Windows so that doesn't really matter that much.

That said, I think it should work. It might be a driver bug.

**Comment by Pilvinen** [comment] 2021-10-20 15:17
I cloned the repository, built the Vulkan validation layers as shown in the first "Build" section here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md

I also tried the Linux section, but those instructions turned out to not work at all.

But I think I got it installed.

Then I started Diablo with the environmental variable exported and got this log:
https://pastebin.com/6GaNWkk7

Can you confirm that I got the validation layers installed and the logs contain what you needed? Because I've never worked with this stuff before and I have basically no idea what I'm doing or what it should look like.

**Comment by Conusoid** [comment] 2021-11-06 21:34
Arch, 5.10.77-3-lts, GTX 770 with nvidia-470xx-dkms 470.82.00-2 driver, latest for this videocard, (can't use newer one since nvidia dropped 700 series support in september 2021).
Lutris 0.5.9.1, DXVK v1.9.2L-3e64e1b, VKD3D v2.4L-a19619c (I believe those already includes all the fixes and patched dlls)
lutris-ge-6.20-1-x86_64
But still black screen with the music. There's no any logs on starting D2R as well as after closing it. I'm desperate :(
Something tells me that it's all videocard's fault...or Blizzard

**Comment by K0bin** [comment] 2021-11-07 00:16
I _think_ that's a driver bug because it works on less ancient GPUs.

**Comment by StepanDav** [comment] 2021-11-21 00:24
Same problem with my "NVIDIA Corporation GM107 [GeForce GTX 750 Ti] (rev a2)", nVidia driver 470.82.00, Debian with kernel 5.7.0-3-amd64 and using Steam / Proton. I have tried both Proton - experimental and Proton-6.21-GE-2, both with the same outcome as original poster.

blz-log.txt: https://pastebin.com/9kc6tJbz
dxdiag.txt: https://pastebin.com/NvxZff9Q

**Comment by Arsakes** [comment] 2021-12-01 01:24
Also a blackscreen with Quadro M1000M, driver 495.44,
OS: Archlinux, 5.10.82-1-lts

Tried patching and various versions of lutris runners, to no avail.
Effect is the same.
Cursor with a black screen.

**Comment by Skucul** [comment] 2021-12-05 00:53
> Also a blackscreen with Quadro M1000M, driver 495.44, OS: Archlinux, 5.10.82-1-lts
> 
> Tried patching and various versions of lutris runners, to no avail. Effect is the same. Cursor with a black screen.

Same problem: Ubuntu 21.10 GTX 860M, tested with driver Nvidia 495.44 and Mesa 21.2.2
both Lutris-GE 6.18 and fshack 6.21-5
v1.9.2L-3e64e1b
VKD3D v2.5L-db89d40

**Comment by Blisto91** [comment] 2021-12-08 23:51
Hi there.
Could some of you try and see if launching with this helps?
```
VKD3D_CONFIG=single_queue
```

**Comment by StepanDav** [comment] 2021-12-09 01:45
> Hi there. Could some of you try and see if launching with this helps?
> 
> ```
> VKD3D_CONFIG=single_queue
> ```

Tried (in Steam in "launch options", I specified "VKD3D_CONFIG=single_queue %command%").

Sadly, it didn't help. No change in apparent behavior of the game.

**Comment by Conusoid** [comment] 2021-12-09 04:59
> ```
> VKD3D_CONFIG=single_queue
> ```
Yep, no effect.

Btw guys. Does anyone else have a change when switching VKD3D version from 2.4 to 2.5? Instead of running game and black screen, now I have just a few secs of black screen and then blizzard crash error.

**Comment by StepanDav** [comment] 2022-06-05 14:44
Having run out of ideas, I have purchased GeForce GTX 960. Consequently, I was also able to update my nVidia drivers (the most recent ones aren't compatible with the GTX 750 that I had previously).

This was enough to make the game work for me.

**Comment by evbo** [comment] 2022-08-07 05:31
just curious, also with a GTX 750 and wondering is this likely a won't fix issue? Or could there be hope yet for us ancient dinosaur GPUs?

**Comment by Conusoid** [comment] 2022-08-07 06:38
> Or could there be hope yet for us ancient dinosaur GPUs?

I highly doubt it. The good news is that video cards are getting cheaper every day.

**Comment by K0bin** [comment] 2022-08-07 10:23
VKD3D-Proton doesn't support ancient GPUs like the 750 anymore.

**Comment by evbo** [comment] 2022-08-07 13:22
I guess Nouveau open source drivers have the _potential_ to resolve this (haven't tried their driver yet but if I get another opportunity may give it a shot)

**Comment by Goddard** [comment] 2022-12-07 11:02
22.10 here with a 3080 laptop GPU and I also tried with my eGPU which is a desktop 3080.  Tried with 520 and 525 nvidia driver.

**Comment by K0bin** [comment] 2022-12-07 11:45
> 22.10 here with a 3080 laptop GPU

What do you mean by 22.10?

**Comment by Goddard** [comment] 2022-12-07 11:52
> > 22.10 here with a 3080 laptop GPU
> 
> What do you mean by 22.10?

https://releases.ubuntu.com/kinetic/

**Closed** 2023-05-14 21:01 UTC
