### ISSUE TITLE
Persona 3 Reload Crash: Out of Video Memory trying to allocate rendering resource

### ISSUE THREAD

**Issue by SirMovekMarwa** [HansKristian-Work/vkd3d-proton#1875] opened 2024-02-02 21:09 UTC
The game runs perfectly up to the first gameplay moment, in the moment in which the game wants to change from the first mini level to the next the game crashes with a window that says "Out of Video Memory trying to allocate rendering resource" 
![Screenshot_20240202_012719](https://github.com/HansKristian-Work/vkd3d-proton/assets/56955386/e55bc984-1b9d-48e5-930a-cf390622c399)

### Software information
Persona 3 Reload, minimal settings. low shadows, no reflections. 30 fps, i've changed from borderless to full screen with 1280x720 no vsync and still nothing. 

### System information
- GPU: GeForce GTX 1050 Ti
- Driver: video-nvidia 545.29.06
- Wine version: wine8.21
- VKD3D-Proton version: GE-Proton8-30

### Log files
[steam-2161700.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14145247/steam-2161700.log)

**Comment by doitsujin** [comment] 2024-02-03 01:17
Log says it's failing to compile pipelines, which I already looked at. This is an Nvidia driver bug that only seems to affect Pascal, but the shaders in question are also incredibly cursed and horrible.

**Comment by AnzoDK** [comment] 2024-02-03 08:47
> Log says it's failing to compile pipelines, which I already looked at. Not sure why the message says anything about VRAM.
> 
> This is an Nvidia driver bug that only seems to affect Pascal, but the shaders in question are also incredibly cursed and horrible.

Is there then no hope for old folks like me with GTX 1070-TIs or should I try a NVIDIA driver downgrade?

**Comment by kelzang-tobgyel** [comment] 2024-02-04 14:38
Same issue here. I'm currently downgrading to various older drivers to see if that'll help. I hope this does get fixed soon though. I'll post again once I've tried 535, and 525.

System information

GPU: GeForce GTX 1050 Mobile
Driver: video-nvidia 545.29.06
Wine version: wine8.21
VKD3D-Proton version: GE-Proton8-30

**Comment by SirMovekMarwa** [comment] 2024-02-05 01:25
@kelzang-tobgyel ... did you found any that worked?

**Comment by SonicSaberYT** [comment] 2024-02-05 03:18
Having the same exact issue

**Comment by kelzang-tobgyel** [comment] 2024-02-05 14:08
> @kelzang-tobgyel ... did you found any that worked?

No luck so far. I'll keep going down the list of past production drivers listed on the NVidia site.

**Comment by HansKristian-Work** [comment] 2024-02-05 22:54
Failed to compile pipeline might be resolved on Pascal now.

**Comment by SirMovekMarwa** [comment] 2024-02-06 04:14
> Failure to compile pipeline might be resolved on Pascal now.

Really? I've seen no changes. Unless i'm missing something (hopefully)

**Comment by SonicSaberYT** [comment] 2024-02-06 13:29
> Failure to compile pipeline might be resolved on Pascal now.

How do I apply the changes

**Comment by HansKristian-Work** [comment] 2024-02-06 13:30
It should be on Proton Hotfix already, and game should be pinned to it now I think.

**Comment by SonicSaberYT** [comment] 2024-02-06 16:13
I found the fix 
    Find Proton Experimental in your Steam Library.
    Open its Properties menu.
    Go to the Betas tab.
    Select "bleeding-edge" from the drop-down box.
    Careful though, this will then make any game you have that's set to Proton Experimental also use the Beta. This is until Valve release a new build of Proton Experimental directly1.
    Now right click P3R you want to run with Proton Experimental and go to its Properties menu.
    Select the Compatibility tab.
    Put a tick in the box and select Proton Experimental.

**Comment by kelzang-tobgyel** [comment] 2024-02-07 06:23
The issue is fixed in the latest bleeding edge version. I haven't tested the 7.0 version yet. Thanks for the work guys, I appreciate you all so much.

**Closed** 2024-02-07 13:40 UTC

**Comment by SirMovekMarwa** [comment] 2024-02-08 04:00
oh my god it actually worked! Thank you everyone!

Thank you so much @HansKristian-Work you're a god sir haha!
